### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jakubhava** [trustin/sphinx-gradle-plugin#11]
Hi @trustin , thanks for the fix of https://github.com/trustin/sphinx-maven-plugin/issues/14 in release 0.3.1 and later. Would it be also please possible to create a new release of this library with the updated dependencies?

Thank you!

Kuba

**Comment by trustin** [comment]
Working on it right now :-)

**Comment by jakubhava** [comment]
amazing, thanks a ton!

**Comment by trustin** [comment]
Enjoy: https://plugins.gradle.org/plugin/kr.motd.sphinx/2.2.3

**Comment by jakubhava** [comment]
just tried, new release 2.2.3 works great, thank you!
