### ISSUE TITLE
Relative path inputs

### ISSUE THREAD

**Issue by firthl** [trustin/sphinx-gradle-plugin#12]
Any chance we can set the path sensitivity annotation on the getSourceDirectory input for SphinxTask?

Just started using the plugin and noticed documentation rebuilds every time, looks like this is due to the directory path changing (branch name and build number is included in build directory path for my CI solution).  

It'd be great if it only build when the file contents of the source directory changed, not the absolute path to the source directory.  

From what I could tell, the new annotation would be: 
@PathSensitive(RELATIVE)

Info on path sensitivity in gradle: 
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#RELATIVE

Location of input to apply it to: 
https://github.com/trustin/sphinx-gradle-plugin/blob/f1cfe4f66ace4f524ac583d3ed8f804e641eab21/src/main/groovy/kr/motd/gradle/sphinx/gradle/SphinxTask.groovy#L81

**Comment by trustin** [comment]
Thanks a lot, @firthl. Just merged your pull request. Let me release a new version shortly.
