### ISSUE TITLE
'doctreeCacheDirectory' does not exist.

### ISSUE THREAD

**Issue by jakubhava** [trustin/sphinx-gradle-plugin#16]
Thank you for providing release 2.7.2 at such amazing speed! I've tried to upgrade to 2.7.2, but getting 
```
> Directory '/Users/kuba/devel/repos/sparkling-water/doc/build/site/.doctrees' specified for property 'doctreeCacheDirectory' does not exist.
```

I'm keeping all the sphinx configuration to default ones

**Comment by jakubhava** [comment]
I can workaround it by creating the `.doctrees` directory inside the build script before running `sphinx` task

**Comment by trustin** [comment]
Should be fixed in 2.8.0. Please let me know if it works for you.

**Comment by jakubhava** [comment]
Thank you, works great!

**Comment by trustin** [comment]
2.9.0 is out today. Could you try that as well?

**Comment by jakubhava** [comment]
Yup, works great as well

**Comment by trustin** [comment]
Thanks for confirmation.
