### ISSUE TITLE
Add option to change configuration directory 

### ISSUE THREAD

**Issue by Ortner** [trustin/sphinx-gradle-plugin#18]
I would like to keep my doc directory as clean as possible. Can you add an option to set the [configuration directory](https://www.sphinx-doc.org/en/master/glossary.html#term-configuration-directory) additional to the source and output directory?

Is that possible?

**Comment by trustin** [comment]
Hi! Sorry I'm late, but I've just release a new version with `configDirectory` option. Please let me know if it works for you!
