### ISSUE TITLE
Using multiple builders

### ISSUE THREAD

**Issue by StFS** [trustin/sphinx-gradle-plugin#3]
There doesn't seem to be any way to specify multiple builders in a single sphinx run. This is the case for both this plugin as well as the main sphinx CLI tool.

That's fine, running sphinx twice is acceptable, however, I'm having problems getting the sphinx-gradle-plugin to do that.

What I've tried is to create a separate task of type SphinxTask and put a sphinx{} block into that task:
```
project(:documentation) {
    task generateText(type: kr.motd.gradle.sphinx.gradle.SphinxTask) {
        sphinx {
            sourceDirectory = "${project.projectDir}"
            outputDirectory = "build/documentation/text"
            builder = "text"
        }
    }

    task generateHtml(type: kr.motd.gradle.sphinx.gradle.SphinxTask) {
        sphinx {
            sourceDirectory = "${project.projectDir}"
            outputDirectory = "build/documentation/text"
            builder = "html"
        }
    }
}
```
which does not work.

The only thing I've gotten to work is this: 
```
project(':documentation') {
    apply plugin: "kr.motd.sphinx"
    sphinx {
        sourceDirectory = "${project.projectDir}"
        outputDirectory = "build/documentation/html"
        builder = "html"
    }
}
```
but the problem with this is that I can only use one builder and I need to create multiple projects somehow to specify multiple sphinx blocks within each project but then I'll have to override the project directory so that both of these project run within the same context.

Am I overlooking something? Is there a simple way to run sphinx with multiple builders on the same source?

**Comment by StFS** [comment]
nevermind! Finally figured it out. Not using the sphinx block inside the task works:

```
project(':documentation') {
    task generateText (type: kr.motd.gradle.sphinx.gradle.SphinxTask){
        builder = "text"
        sourceDirectory = "${project.projectDir}"
        outputDirectory = "build/text"
    }

    task generateHtml (type: kr.motd.gradle.sphinx.gradle.SphinxTask){
        builder = "html"
        sourceDirectory = "${project.projectDir}"
        outputDirectory = "build/html"
    }
}
```

**Comment by trustin** [comment]
Good to hear that you found a way around. Yes, you can always use `SphinxTask` instead of `sphinx { ... }` extension block. :-)

Please feel free to let me know if you have any other inconveniences or suggestions for improvement. :-)
