### ISSUE TITLE
tags doesnt seem to be passing into sphinx property

### ISSUE THREAD

**Issue by sixinli** [trustin/sphinx-gradle-plugin#5]
cant get the tags in `conf.py`

**Comment by trustin** [comment]
What are 'tags'? Could you show me some example?

**Comment by sixinli** [comment]
ah! sorry,... `tags` as in https://trustin.github.io/sphinx-gradle-plugin/configuration.html ... i dont think sphinx is picking it up? (i.e. i have `tags ["test"]` and sphinx `tags` is empty)

**Comment by trustin** [comment]
Could you try the version 1.0.6 which includes the fix (0ca2182ed3295049ab88f87d11d33521fe251ae6)?

On the other hand, `tags` in `conf.py` is not a dictionary. You need to use `tags.has('myTag')`. See [here](https://github.com/trustin/sphinx-gradle-plugin/blob/sphinx-gradle-plugin-1.0.6/src/site/sphinx/conf.py#L7) for a working example.
