### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by xtianus** [trustin/sphinx-gradle-plugin#8]
Running the gradle plugin on an empty project (the default from the tutorial) is very slow compared to the official make file.
Can this be improved?

**Comment by trustin** [comment]
I tried hard to improve the startup time of Sphinx but most attempts ended up with failure. The main bottleneck is Jython and it takes quite a bit of time for loading various modules.

**Comment by trustin** [comment]
We may want to switch to the official Python interpreter using https://github.com/pantsbuild/pex or something similar, but never tried yet.

**Comment by trustin** [comment]
Just released `sphinx-gradle-plugin-2.0.0` which should reduce the build time significantly. Could you let me know if the new release helps you as well?

**Comment by trustin** [comment]
Just released 2.0.2 with some fixes.

**Comment by trustin** [comment]
According to my test, a project that took 50 seconds to generate now takes only 12 seconds. Please open a new issue if you still have performance issues after upgrading.

**Comment by xtianus** [comment]
I wanted to quickly check the speed improvement but I got this error:
`AttributeError: module 'sphinx_bootstrap_theme' has no attribute 'get_html_theme_path'`
It might be my mistake though. I'm in a rush right now.

**Comment by trustin** [comment]
That's interesting. Are you using sphinx_bootstrap_theme in your project? If so, could you try with the default theme? If not, could you share your project?

**Comment by trustin** [comment]
I guess it will just work if you remove the following line from your `conf.py`:

    html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

Sphinx will find the theme just fine without that statement.

**Comment by trustin** [comment]
Actually, it seems not to be the case for sphinx_bootstrap_theme. I didn't notice this issue because I was using sphinx_rtd_theme, which works just fine without html_theme_path. Until I fix this issue properly, could you try using sphinx_rtd_theme to see if the problem goes away?

**Comment by trustin** [comment]
Just released `sphinx-gradle-plugin` 2.2.0 which should fix this problem. Could you please give it a try?

**Comment by xtianus** [comment]
Windows 10, Intel i7-7500U, 16GB RAM, Samsung SSD

**Comment by trustin** [comment]
Cool. I was somewhat worried about Windows performance because Windows tends to be slower than *nix OSes in terms of temporary file creation.
