### ISSUE TITLE
Using javasphinx-apidoc

### ISSUE THREAD

**Issue by xtianus** [trustin/sphinx-gradle-plugin#9]
I don't understand if javasphinx-apidoc is supported and how to use it.
I'd expect it to be invoked by gradle on the java source folders, but I don't see any output.

Sorry to ask questions in an "issue".

**Comment by trustin** [comment]
Hello @xtianus,

I did not try to use `javasphinx-apidoc` but it seems like it is a command-line tool you need to install by yourself. We could improve the plugin so it invokes the command before launching Sphinx, but it's not implemented currently.

Just in case you didn't check the official documentation of javasphinx: http://bronto-javasphinx.readthedocs.io/en/latest/

**Comment by trustin** [comment]
By the way, is it ever better than Javadoc? What's the benefit of using `javasphinx-apidoc`?

**Comment by xtianus** [comment]
I'm very new to sphinx. The only advantage I've seen so far is that with javasphinx-apidoc you can reference an api page by just using the class/method name, instead of using the full link to the javadoc. But now that I think of it, probably you can do the same by means of the javadoc_url_map.

**Comment by trustin** [comment]
Let me close this issue for now. Please feel free to open a new issue if you find issues with javasphinx.
